[build]
  publish = "dist"
  command = "npm run build"

# Environment variables (these need to be set in Netlify dashboard)
# SUPABASE_URL=https://your-project.supabase.co
# SUPABASE_ANON_KEY=your-anon-key
# BIRDEYE_API_KEY=your-birdeye-api-key

# Build settings
[build.environment]
  NODE_VERSION = "18"

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Redirect for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
